version: '3.5'
services:
  db:
    image: mysql:5.7
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_DATABASE: 'touragency'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    volumes:
      - touragency:/var/lib/mysql
      - ./scripts/tourAgencyScript.sql:/docker-entrypoint-initdb.d/1.sql

volumes:
  touragency: